import mongoose from 'mongoose';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const TANGLISH_TO_TAMIL_MAP = {
  // Requirement 10 core mappings
  'vengayam': 'வெங்காயம்',
  'kathirikai': 'கத்திரிக்காய்',
  'kathirikkai': 'கத்திரிக்காய்',
  'murungakkai': 'முருங்கைக்காய்',
  'vendakkai': 'வெண்டைக்காய்',
  'sarkkarai': 'சர்க்கரை',
  'thool uppu': 'தூள் உப்பு',
  'kallu uppu': 'கல் உப்பு',
  'naatu sarkkarai': 'நாட்டு சர்க்கரை',
  'poondu': 'பூண்டு',
  'thakkali': 'தக்காளி',
  'urulaikizhangu': 'உருளைக்கிழங்கு',

  // Comprehensive seed & grocery mappings
  'chinna vengayam': 'சின்ன வெங்காயம்',
  'beetroot': 'பீட்ரூட்',
  'carrot': 'கேரட்',
  'suraikkai': 'சுரைக்காய்',
  'pavakkai': 'பாகற்காய்',
  'peerkangai': 'பீர்கங்காய்',
  'pudalangai': 'புடலங்காய்',
  'poosanikai': 'பூசணிக்காய்',
  'vazhakkai': 'வாழைக்காய்',
  'pachai milagai': 'பச்சை மிளகாய்',
  'inji': 'இஞ்சி',
  'muttakose': 'முட்டைகோஸ்',
  'cauliflower': 'காலிபிளவர்',
  'beans': 'பீன்ஸ்',
  'mullangi': 'முள்ளங்கி',
  'kothavarangai': 'கொத்தவரங்காய்',
  'avarakkai': 'அவரைக்காய்',
  'kovakkai': 'கோவக்காய்',
  'vellai poosani': 'வெள்ளை பூசணி',
  'seemai kathirikkai': 'சீமை கத்திரிக்காய்',
  'kothamalli': 'கொத்தமல்லி',
  'pudina': 'புதினா',
  'karuveppilai': 'கறிவேப்பிலை',
  'palak keerai': 'பாலக் கீரை',
  'shimla apple': 'சிம்லா ஆப்பிள்',
  'washington apple': 'வாஷிங்டன் ஆப்பிள்',
  'alphonso maampazham': 'அல்போன்சா மாம்பழம்',
  'banganapalli maampazham': 'பங்கனப்பள்ளி மாம்பழம்',
  'imam pasand maampazham': 'இமாம் பசந்த் மாம்பழம்',
  'rasalu maampazham': 'ரசாலு மாம்பழம்',
  'pachai vazhaipazham': 'பச்சை வாழைப்பழம்',
  'poovan pazham': 'பூவன் பழம்',
  'nendran pazham': 'நேந்திரன் பழம்',
  'sevvalai pazham': 'செவ்வாழை பழம்',
  'aaranju': 'ஆரஞ்சு',
  'sathukudi': 'சாத்துக்குடி',
  'mathalam pazham': 'மாதுளம்பழம்',
  'pappali pazham': 'பப்பாளி பழம்',
  'tharboosani': 'தர்பூசணி',
  'anachi pazham': 'அன்னாசி பழம்',
  'koyya pazham': 'கொய்யா பழம்',
  'pachai thiratchai': 'பச்சை திராட்சை',
  'good day butter': 'குட் டே பட்டர்',
  'good day cashew': 'குட் டே முந்திரி',
  'marie gold': 'மேரி கோல்ட்',
  '50-50 maska chaska': '50-50 மஸ்கா சஸ்கா',
  'milky bar': 'மில்கி பார்',
  'nutrichoice digestive': 'நியூட்ரிசாய்ஸ் டைஜெஸ்டிவ்',
  'jim jam': 'ஜிம் ஜாம்',
  'chulbule': 'சுல்புலே',
  'dark fantasy': 'டார்க் பேண்டஸி',
  'monaco salted': 'மொனாக்கோ சால்டட்',
  'parle-g original': 'பார்லே-ஜி',
  'oreo vanilla': 'ஓரியோ வெண்ணிலா',
  'bounce double choco': 'பவுன்ஸ் டபுள் சாக்கோ',
  'treat strawberry': 'ட்ரீட் ஸ்ட்ராபெரி',
  'little hearts': 'லிட்டில் ஹார்ட்ஸ்',
  'hide & seek': 'ஹைடு & சீக்',
  'krackjack': 'கிராக்ஜாக்',
  'potato chips salted': 'உருளைக்கிழங்கு சிப்ஸ்',
  'cheesy wafers': 'சீஸ் வேஃபர்ஸ்',
  'butter murukku': 'பட்டர் முறுக்கு',
  'ribbon pakoda': 'ரிப்பன் பக்கோடா',
  'kara sev': 'கார சேவ்',
  'masala peanuts': 'மசாலா கடலை',
  'mixture': 'மிக்சர்',
  'banana chips': 'வாழைக்காய் சிப்ஸ்',
  'tapioca chips': 'மரவள்ளிக்கிழங்கு சிப்ஸ்',
  'kai murukku': 'கை முறுக்கு',
  'thattai': 'தட்டை',
  'seeval': 'சீவல்',
  'boondi': 'பூந்தி',
  'samosa': 'சமோசா',
  'kachori': 'கச்சோரி',
  'jalebi': 'ஜிலேபி',
  'mysore pak': 'மைசூர் பாக்கு',
  'laddu': 'லட்டு',
  'soan papdi': 'சோன் பப்டி',
  'halwa': 'அல்வா',
  'badam milk': 'பாதாம் பால்',
  'rose milk': 'ரோஸ் மில்க்',
  'curd': 'தயிர்',
  'paneer': 'பன்னீர்',
  'ghee': 'நெய்',
  'butter': 'வெண்ணெய்',
  'cheese cubes': 'சீஸ் கியூப்ஸ்',
  'condensed milk': 'கண்டன்ஸ்ட் மில்க்',
  'masala powder': 'மசாலா தூள்',
  'turmeric powder': 'மஞ்சள் தூள்',
  'chilli powder': 'மிளகாய் தூள்',
  'coriander powder': 'கொத்தமல்லி தூள்',
  'garam masala': 'கரம் மசாலா',
  'sambar powder': 'சாம்பார் தூள்',
  'rasam powder': 'ரசம் தூள்',
  'biryani masala': 'பிரியாணி மசாலா',
  'chicken masala': 'சிக்கன் மசாலா',
  'mutton masala': 'மட்டன் மசாலா',
  'fish curry masala': 'மீன் குழம்பு மசாலா',
  'pepper powder': 'மிளகு தூள்',
  'cumin powder': 'சீரகத் தூள்',
  'fennel powder': 'சோம்பு தூள்',
  'asafoetida': 'பெருங்காயம்',
  'fenugreek': 'வெந்தயம்',
  'mustard seeds': 'கடுகு',
  'urad dal': 'உளுத்தம்பருப்பு',
  'chana dal': 'கடலைப்பருப்பு',
  'moong dal': 'பாசிப்பருப்பு',
  'toor dal': 'துவரம்பருப்பு',
  'ponni rice': 'பொன்னி அரிசி',
  'basmati rice': 'பாசுமதி அரிசி',
  'idli rice': 'இட்லி அரிசி',
  'wheat flour': 'கோதுமை மாவு',
  'maida': 'மைதா மாவு',
  'besan flour': 'கடலை மாவு',
  'rice flour': 'அரிசி மாவு',
  'ragi flour': 'ராகி மாவு',
  'rava': 'ரவை',
  'vermicelli': 'சேமியா',
  'poha': 'அவுல்',
  'sunflower oil': 'சூரியகாந்தி எண்ணெய்',
  'groundnut oil': 'கடலை எண்ணெய்',
  'gingelly oil': 'நல்லெண்ணெய்',
  'coconut oil': 'தேங்காய் எண்ணெய்',
  'mustard oil': 'கடுகு எண்ணெய்',
  'castor oil': 'விளக்கெண்ணெய்',
  'palm oil': 'பாமாயில்',
  'olive oil': 'ஆலிவ் எண்ணெய்',
  'lemon pickle': 'எலுமிச்சை ஊறுகாய்',
  'mango pickle': 'மாங்காய் ஊறுகாய்',
  'garlic pickle': 'பூண்டு ஊறுகாய்',
  'tomato pickle': 'தக்காளி ஊறுகாய்',
  'mixed vegetable pickle': 'காய்கறி ஊறுகாய்',
  'dishwash liquid': 'பாத்திரம் கழுவும் திரவம்',
  'floor cleaner': 'தரை சுத்தம் செய்யும் திரவம்',
  'detergent powder': 'சலவை தூள்',
  'detergent cake': 'சலவை சோப்பு',
  'toilet cleaner': 'கழிப்பறை சுத்தம் செய்யும் திரவம்',
  'glass cleaner': 'கண்ணாடி சுத்தம் செய்யும் திரவம்',
  'thakkali': 'தக்காளி',
  'vengayam': 'வெங்காயம்',
  'urulaikizhangu': 'உருளைக்கிழங்கு',
  'kathirikka': 'கத்திரிக்காய்',
  'vendaikkai': 'வெண்டைக்காய்',
  'kudamilagai': 'குடைமிளகாய்',
  'muttaikose': 'முட்டைகோஸ்',
  'vaazhai kaai': 'வாழைக்காய்',
  'vendhaya keerai': 'வெந்தயக் கீரை',
  'araikeerai': 'அரைக்கீரை',
  'vazhaipazham': 'வாழைப்பழம்',
  'pappali': 'பப்பாளி',
  'thiratchai': 'திராட்சை',
  'paal': 'பால்',
  'thayir': 'தயிர்',
  'vennai': 'வெண்ணெய்',
  'cheese': 'சீஸ்',
  'biscuit': 'பிஸ்கட்',
  'chips': 'சிப்ஸ்',
  'aachi chicken masala': 'ஆச்சி சிக்கன் மசாலா',
  'aachi mutton masala': 'ஆச்சி மட்டன் மசாலா',
  'aachi sambar thool': 'ஆச்சி சாம்பார் தூள்',
  'aachi rasam thool': 'ஆச்சி ரசம் தூள்',
  'aachi milagai thool': 'ஆச்சி மிளகாய் தூள்',
  'aachi manjal thool': 'ஆச்சி மஞ்சள் தூள்',
  'aachi kothamalli thool': 'ஆச்சி கொத்தமல்லி தூள்',
  'aachi garam masala': 'ஆச்சி கரம் மசாலா',
  'aachi biryani masala': 'ஆச்சி பிரியாணி மசாலா',
  'aachi milagu thool': 'ஆச்சி மிளகு தூள்',
  'maangai oorukai': 'மாங்காய் ஊறுகாய்',
  'elumichai oorukai': 'எலுமிச்சை ஊறுகாய்',
  'poondu oorukai': 'பூண்டு ஊறுகாய்',
  'mixed oorukai': 'காய்கறி ஊறுகாய்',
  'thakkali oorukai': 'தக்காளி ஊறுகாய்',
  'inji oorukai': 'இஞ்சி ஊறுகாய்',
  'nellikai oorukai': 'நெல்லிக்காய் ஊறுகாய்',
  'pachai milagai oorukai': 'பச்சை மிளகாய் ஊறுகாய்',
  'surf excel powder': 'சர்ஃப் எக்செல் தூள்',
  'rin powder': 'ரின் தூள்',
  'ariel matic': 'ஏரியல் மேடிக்',
  'tide plus': 'டைடு பிளஸ்',
  'wheel powder': 'வீல் தூள்',
  'henko powder': 'ஹென்கோ தூள்',
  'surf excel liquid': 'சர்ஃப் எக்செல் திரவம்',
  'vim gel': 'விம் ஜெல்',
  'exo soap': 'எக்சோ சோப்பு',
  'aavin green paal': 'ஆவின் கிரீன் பால்',
  'aavin blue paal': 'ஆவின் ப்ளூ பால்',
  'arokya paal': 'ஆரோக்யா பால்',
  'getti thayir': 'கெட்டி தயிர்',
  'pasu neyi': 'பசு நெய்',
  'masala mor': 'மசாலா மோர்',
  'rose milk': 'ரோஸ் மில்க்',
  'yogurt': 'யோகர்ட்',
  'lays yellow': 'லேஸ் மஞ்சள் சிப்ஸ்',
  'lays blue': 'லேஸ் நீல சிப்ஸ்',
  'lays green': 'லேஸ் பச்சை சிப்ஸ்',
  'lays red': 'லேஸ் சிவப்பு சிப்ஸ்',
  'kurkure': 'குர்குரே',
  'bingo triangle': 'பிங்கோ சிப்ஸ்',
  'kai murukku': 'கை முறுக்கு',
  'madras mixture': 'மெட்ராஸ் மிக்சர்',
  'sunflower ennai': 'சூரியகாந்தி எண்ணெய்',
  'fortune ennai': 'பார்ச்சூன் எண்ணெய்',
  'mara sekku kadalai ennai': 'மரச்செக்கு கடலை எண்ணெய்',
  'idhayam nallennai': 'இதயம் நல்லெண்ணெய்',
  'vvd thengai ennai': 'விவிடி தேங்காய் எண்ணெய்',
  'rice bran ennai': 'ரைஸ் பிரான் எண்ணெய்',
  'kadugu ennai': 'கடுகு எண்ணெய்',
  'palmolein ennai': 'பாமாயில் எண்ணெய்',
  'anjali nallennai': 'அஞ்சலி நல்லெண்ணெய்',
  'malai poondu': 'மலை பூண்டு',
  'pollachi thengai': 'பொள்ளாச்சி தேங்காய்',
  'bru coffee': 'ப்ரூ காபி தூள்',
  'sunrise coffee': 'சன்ரைஸ் காபி தூள்',
  '3 roses tea': '3 ரோசஸ் தேயிலை',
  'chakra gold tea': 'சக்ரா கோல்ட் தேயிலை',
  'mandavellam / naattu sarkkarai': 'நாட்டு சர்க்கரை / வெல்லம்',
  'sarkkarai': 'சர்க்கரை',
  'kallu uppu': 'கல் உப்பு',
  'thool uppu': 'தூள் உப்பு'
};

export const ENGLISH_TO_TAMIL_MAP = {
  'tomato': 'தக்காளி',
  'onion': 'வெங்காயம்',
  'potato': 'உருளைக்கிழங்கு',
  'carrot': 'கேரட்',
  'brinjal': 'கத்திரிக்காய்',
  'lady finger': 'வெண்டைக்காய்',
  'ladies finger': 'வெண்டைக்காய்',
  'capsicum': 'குடைமிளகாய்',
  'cauliflower': 'காலிபிளவர்',
  'cabbage': 'முட்டைகோஸ்',
  'drumstick': 'முருங்கைக்காய்',
  'bitter gourd': 'பாகற்காய்',
  'raw banana': 'வாழைக்காய்',
  'spinach': 'பாலக் கீரை',
  'fenugreek leaves': 'வெந்தயக் கீரை',
  'coriander leaves': 'கொத்தமல்லி',
  'curry leaves': 'கறிவேப்பிலை',
  'mint leaves': 'புதினா',
  'amaranth greens': 'அரைக்கீரை',
  'banana': 'வாழைப்பழம்',
  'mango': 'மாம்பழம்',
  'papaya': 'பப்பாளி',
  'apple': 'ஆப்பிள்',
  'pomegranate': 'மாதுளம்பழம்',
  'watermelon': 'தர்பூசணி',
  'orange': 'ஆரஞ்சு',
  'grapes': 'திராட்சை',
  'fresh milk': 'பால்',
  'curd': 'தயிர்',
  'paneer': 'பன்னீர்',
  'butter': 'வெண்ணெய்',
  'cheese slices': 'சீஸ்',
  'murukku': 'முறுக்கு',
  'mixture': 'மிக்சர்',
  'biscuits': 'பிஸ்கட்',
  'chips': 'சிப்ஸ்',
  'small onion (shallots)': 'சின்ன வெங்காயம்',
  'small onion': 'சின்ன வெங்காயம்',
  'beetroot': 'பீட்ரூட்',
  'bottle gourd': 'சுரைக்காய்',
  'ridge gourd': 'பீர்கங்காய்',
  'snake gourd': 'புடலங்காய்',
  'yellow pumpkin': 'பூசணிக்காய்',
  'green chilli': 'பச்சை மிளகாய்',
  'ginger': 'இஞ்சி',
  'french beans': 'பீன்ஸ்',
  'white radish': 'முள்ளங்கி',
  'cluster beans': 'கொத்தவரங்காய்',
  'broad beans': 'அவரைக்காய்',
  'ivy gourd': 'கோவக்காய்',
  'ash gourd': 'வெள்ளை பூசணி',
  'chow chow': 'சீமை கத்திரிக்காய்',
  'indian apple': 'சிம்லா ஆப்பிள்',
  'washington apple': 'வாஷிங்டன் ஆப்பிள்',
  'alphonso mango': 'அல்போன்சா மாம்பழம்',
  'banganapalli mango': 'பங்கனப்பள்ளி மாம்பழம்',
  'imam pasand mango': 'இமாம் பசந்த் மாம்பழம்',
  'rasalu mango': 'ரசாலு மாம்பழம்',
  'robusta banana': 'பச்சை வாழைப்பழம்',
  'poovan banana': 'பூவன் பழம்',
  'nendran banana': 'நேந்திரன் பழம்',
  'red banana': 'செவ்வாழை பழம்',
  'sweet lime': 'சாத்துக்குடி',
  'pineapple': 'அன்னாசி பழம்',
  'guava': 'கொய்யா பழம்',
  'green grapes': 'பச்சை திராட்சை',
  'good day butter cookies': 'குட் டே பட்டர்',
  'good day cashew cookies': 'குட் டே முந்திரி',
  'marie gold biscuit': 'மேரி கோல்ட்',
  'tiger glucose biscuit': 'டைகர் பிஸ்கட்',
  'bourbon chocolate cream': 'போர்பன் பிஸ்கட்',
  'milk bikis': 'மில்க் பிகிஸ்',
  'oreo original chocolate cookies': 'ஓரியோ பிஸ்கட்',
  'parle hide & seek choco rolls': 'ஹைடு & சீக்',
  'britannia 50-50 sweet & salty': '50-50 பிஸ்கட்',
  'monaco salted crackers': 'மொனாக்கோ பிஸ்கட்',
  'krackjack sweet & salty crackers': 'கிராக்ஜாக் பிஸ்கட்',
  'aachi chicken masala': 'ஆச்சி சிக்கன் மசாலா',
  'aachi mutton masala': 'ஆச்சி மட்டன் மசாலா',
  'aachi sambar powder': 'ஆச்சி சாம்பார் தூள்',
  'aachi rasam powder': 'ஆச்சி ரசம் தூள்',
  'aachi chilli powder': 'ஆச்சி மிளகாய் தூள்',
  'aachi turmeric powder': 'ஆச்சி மஞ்சள் தூள்',
  'aachi coriander powder': 'ஆச்சி கொத்தமல்லி தூள்',
  'aachi garam masala': 'ஆச்சி கரம் மசாலா',
  'aachi biryani masala': 'ஆச்சி பிரியாணி மசாலா',
  'aachi pepper powder': 'ஆச்சி மிளகு தூள்',
  'aachi cut mango pickle': 'மாங்காய் ஊறுகாய்',
  'aachi lemon pickle': 'எலுமிச்சை ஊறுகாய்',
  'aachi garlic pickle': 'பூண்டு ஊறுகாய்',
  'aachi mixed vegetable pickle': 'காய்கறி ஊறுகாய்',
  'aachi tomato pickle': 'தக்காளி ஊறுகாய்',
  'aachi ginger pickle': 'இஞ்சி ஊறுகாய்',
  'aachi gooseberry pickle': 'நெல்லிக்காய் ஊறுகாய்',
  'aachi green chilli pickle': 'பச்சை மிளகாய் ஊறுகாய்',
  'surf excel easy wash powder': 'சர்ஃப் எக்செல் தூள்',
  'rin refresh detergent powder': 'ரின் தூள்',
  'ariel matic front load detergent': 'ஏரியல் மேடிக்',
  'tide plus double power jasmine': 'டைடு பிளஸ்',
  'wheel active 2 in 1 lemon & jasmine': 'வீல் தூள்',
  'henko stain champion powder': 'ஹென்கோ தூள்',
  'surf excel matic liquid detergent': 'சர்ஃப் எக்செல் திரவம்',
  'vim lemon dishwash gel': 'விம் ஜெல்',
  'exo touch & shine round bar': 'எக்சோ சோப்பு',
  'aavin green standardized milk': 'ஆவின் கிரீன் பால்',
  'aavin blue toned milk': 'ஆவின் ப்ளூ பால்',
  'arokya full cream milk': 'ஆரோக்யா பால்',
  'fresh farm curd': 'கெட்டி தயிர்',
  'aavin pure cow ghee': 'பசு நெய்',
  'spiced buttermilk': 'மசாலா மோர்',
  'cavins rose flavoured milk': 'ரோஸ் மில்க்',
  'milky mist greek yogurt': 'யோகர்ட்',
  'lays classic salted potato chips': 'லேஸ் மஞ்சள் சிப்ஸ்',
  'lays india’s magic masala': 'லேஸ் நீல சிப்ஸ்',
  'lays american style cream & onion': 'லேஸ் பச்சை சிப்ஸ்',
  'lays spanish tomato tango': 'லேஸ் சிவப்பு சிப்ஸ்',
  'kurkure masala munch': 'குர்குரே',
  'bingo mad angles achaari masti': 'பிங்கோ சிப்ஸ்',
  'traditional south indian murukku': 'கை முறுக்கு',
  'madras spicy mixture': 'மெட்ராஸ் மிக்சர்',
  'gold winner refined sunflower oil': 'சூரியகாந்தி எண்ணெய்',
  'fortune sunlite sunflower oil': 'பார்ச்சூன் எண்ணெய்',
  'traditional cold pressed groundnut oil': 'மரச்செக்கு கடலை எண்ணெய்',
  'idhayam gingelly oil (sesame)': 'இதயம் நல்லெண்ணெய்',
  'vvd gold pure coconut oil': 'விவிடி தேங்காய் எண்ணெய்',
  'freedom rice bran oil': 'ரைஸ் பிரான் எண்ணெய்',
  'fortune kachi ghani mustard oil': 'கடுகு எண்ணெய்',
  'ruchi gold palm oil': 'பாமாயில் எண்ணெய்',
  'anjali cold pressed gingelly oil': 'அஞ்சலி நல்லெண்ணெய்',
  'garlic (country variety)': 'மலை பூண்டு',
  'fresh mature coconut': 'பொள்ளாச்சி தேங்காய்',
  'bru instant coffee powder': 'ப்ரூ காபி தூள்',
  'nescafe sunrise rich coffee': 'சன்ரைஸ் காபி தூள்',
  '3 roses dust tea powder': '3 ரோசஸ் தேயிலை',
  'chakra gold premium tea powder': 'சக்ரா கோல்ட் தேயிலை',
  'organic chemical-free jaggery': 'நாட்டு சர்க்கரை / வெல்லம்',
  'refined white sugar': 'சர்க்கரை',
  'tata crystal sea salt': 'கல் உப்பு',
  'tata vacuum evaporated iodized salt': 'தூள் உப்பு'
};

export function cleanAndConvertTamilName(rawVal, engName) {
  let cleaned = '';
  if (rawVal && typeof rawVal === 'string') {
    cleaned = rawVal.replace(/^\s*\((.*)\)\s*$/, '$1').trim();
    const lower = cleaned.toLowerCase();
    if (TANGLISH_TO_TAMIL_MAP[lower]) {
      return TANGLISH_TO_TAMIL_MAP[lower];
    }
  }
  if (engName && typeof engName === 'string') {
    const engLower = engName.trim().toLowerCase();
    if (ENGLISH_TO_TAMIL_MAP[engLower]) {
      return ENGLISH_TO_TAMIL_MAP[engLower];
    }
  }
  return cleaned || (engName ? '' : '');
}

export async function ensureTamilFontDownloaded() {
  try {
    const fontDir = path.resolve(__dirname, '../../frontend/public/fonts');
    const fontPath = path.join(fontDir, 'NotoSansTamil-Regular.ttf');
    if (fs.existsSync(fontPath)) {
      return;
    }
    if (!fs.existsSync(fontDir)) {
      fs.mkdirSync(fontDir, { recursive: true });
    }
    console.log('[Font Loader] Downloading NotoSansTamil-Regular.ttf for local PDF rendering...');
    const res = await fetch('https://raw.githubusercontent.com/googlefonts/noto-fonts/main/hinted/ttf/NotoSansTamil/NotoSansTamil-Regular.ttf');
    if (res.ok) {
      const arrayBuf = await res.arrayBuffer();
      fs.writeFileSync(fontPath, Buffer.from(arrayBuf));
      console.log('[Font Loader] Successfully saved NotoSansTamil-Regular.ttf to frontend/public/fonts/');
    }
  } catch (err) {
    console.warn('[Font Loader] Note: Could not auto-download font:', err.message);
  }
}

export async function migrateTamilNames() {
  try {
    await ensureTamilFontDownloaded();
    console.log('[Migration] Checking products for Tanglish -> Tamil Unicode conversion...');
    const productsColl = mongoose.connection.db.collection('products');
    const allProducts = await productsColl.find({}).toArray();
    let updatedCount = 0;

    for (const prod of allProducts) {
      const existingVal = prod.tamilName || prod.nameTamil || '';
      const converted = cleanAndConvertTamilName(existingVal, prod.name);
      
      const needsUpdate = (prod.nameTamil !== converted) || (prod.tamilName !== converted) || (!prod.tamilName);
      if (needsUpdate && converted) {
        await productsColl.updateOne(
          { _id: prod._id },
          {
            $set: {
              nameTamil: converted,
              tamilName: converted
            }
          }
        );
        updatedCount++;
      }
    }
    console.log(`[Migration] Completed! Successfully verified/converted ${updatedCount} products to Tamil Unicode.`);
  } catch (err) {
    console.error('[Migration Error] Failed to migrate Tamil product names:', err);
  }
}
